/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista.operadoraTelefonica;

import ec.edu.ups.ejemplo.diez.controlador.OperadoraTelefonicaControlador;
import ec.edu.ups.ejemplo.diez.modelo.OperadoraTelefonica;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaActualizarOperadoraTelefonica extends javax.swing.JInternalFrame {

    private OperadoraTelefonicaControlador operadoraTelefonicaControlador;

    /**
     * Creates new form VentanaActualizarPersona
     */
    public VentanaActualizarOperadoraTelefonica(OperadoraTelefonicaControlador operadoraTelefonicaControlador) {
        initComponents();
        this.operadoraTelefonicaControlador = operadoraTelefonicaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarOperadora = new javax.swing.JPanel();
        lblCodigoActualizarOperadoraTelefonica = new javax.swing.JLabel();
        lblNombreActualizarOperadoraTelefonica = new javax.swing.JLabel();
        txtCodigoActualizarOperadoraTelefonica = new javax.swing.JTextField();
        txtNombreActualizarOperadoraTelefonica = new javax.swing.JTextField();
        btnActualizarActualizarOperadoraTelefonica = new javax.swing.JButton();
        btnCancelarActualizarOperadoraTelefonica = new javax.swing.JButton();
        btnBuscarActualizarOperadoraTelefonica = new javax.swing.JButton();

        panelActualizarOperadora.setBackground(new java.awt.Color(204, 204, 255));
        panelActualizarOperadora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Operadora Telefonica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        lblCodigoActualizarOperadoraTelefonica.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCodigoActualizarOperadoraTelefonica.setText("Codigo:");

        lblNombreActualizarOperadoraTelefonica.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombreActualizarOperadoraTelefonica.setText("Nombre:");

        txtCodigoActualizarOperadoraTelefonica.setToolTipText("Ingrese la nueva cedula de la persona");
        txtCodigoActualizarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActualizarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        txtNombreActualizarOperadoraTelefonica.setToolTipText("Ingrese el nuevo nombre de de la persona");
        txtNombreActualizarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        btnActualizarActualizarOperadoraTelefonica.setText("Actualizar");
        btnActualizarActualizarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActualizarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        btnCancelarActualizarOperadoraTelefonica.setText("Cancelar");
        btnCancelarActualizarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        btnBuscarActualizarOperadoraTelefonica.setText("Buscar");
        btnBuscarActualizarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActualizarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarOperadoraLayout = new javax.swing.GroupLayout(panelActualizarOperadora);
        panelActualizarOperadora.setLayout(panelActualizarOperadoraLayout);
        panelActualizarOperadoraLayout.setHorizontalGroup(
            panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarOperadoraLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoActualizarOperadoraTelefonica)
                    .addComponent(lblNombreActualizarOperadoraTelefonica))
                .addGap(131, 131, 131)
                .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreActualizarOperadoraTelefonica, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtCodigoActualizarOperadoraTelefonica)
                    .addGroup(panelActualizarOperadoraLayout.createSequentialGroup()
                        .addComponent(btnActualizarActualizarOperadoraTelefonica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarActualizarOperadoraTelefonica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarActualizarOperadoraTelefonica)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelActualizarOperadoraLayout.setVerticalGroup(
            panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarOperadoraLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigoActualizarOperadoraTelefonica)
                    .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoActualizarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarActualizarOperadoraTelefonica)))
                .addGap(21, 21, 21)
                .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizarOperadoraTelefonica)
                    .addComponent(txtNombreActualizarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarOperadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarActualizarOperadoraTelefonica)
                    .addComponent(btnCancelarActualizarOperadoraTelefonica))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarOperadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarOperadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActualizarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarOperadoraTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizarOperadoraTelefonicaActionPerformed

    private void txtCodigoActualizarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActualizarOperadoraTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActualizarOperadoraTelefonicaActionPerformed

    private void btnActualizarActualizarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActualizarOperadoraTelefonicaActionPerformed
        
        
        int codigo = Integer.parseInt(txtCodigoActualizarOperadoraTelefonica.getText());
        String nombre = txtNombreActualizarOperadoraTelefonica.getText();
                
        OperadoraTelefonica operadoraTelefonica = new OperadoraTelefonica();
        operadoraTelefonica.setCodigo(codigo);
        operadoraTelefonica.setNombre(nombre);
        
        if(operadoraTelefonicaControlador.actualizar(operadoraTelefonica)){
            JOptionPane.showMessageDialog(this, "La persona ha sido actualizada exitosamente! :)");
            this.limpiarCampos();   
            this.cambiarEstadoCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "La persona no ha sido actualizada! :(");
        }

    }//GEN-LAST:event_btnActualizarActualizarOperadoraTelefonicaActionPerformed

    private void btnCancelarActualizarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarOperadoraTelefonicaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActualizarOperadoraTelefonicaActionPerformed

    private void btnBuscarActualizarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarOperadoraTelefonicaActionPerformed
        int codigo = Integer.parseInt(txtCodigoActualizarOperadoraTelefonica.getText());
        OperadoraTelefonica operadoraTelefonica = operadoraTelefonicaControlador.buscar(codigo);
        if (operadoraTelefonica != null) {
            txtNombreActualizarOperadoraTelefonica.setText(operadoraTelefonica.getNombre());
            this.cambiarEstadoCampos(true);
        } else {
            JOptionPane.showMessageDialog(this, "La operadora con codigo" + codigo + " no ha sido encontrada!");
        }
    }//GEN-LAST:event_btnBuscarActualizarOperadoraTelefonicaActionPerformed
    private void limpiarCampos() {
        this.txtCodigoActualizarOperadoraTelefonica.setText("");
        this.txtNombreActualizarOperadoraTelefonica.setText("");
    }

    private void cambiarEstadoCampos(boolean estado) {
        this.txtCodigoActualizarOperadoraTelefonica.setEnabled(estado);
        this.txtNombreActualizarOperadoraTelefonica.setEnabled(estado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActualizarOperadoraTelefonica;
    private javax.swing.JButton btnBuscarActualizarOperadoraTelefonica;
    private javax.swing.JButton btnCancelarActualizarOperadoraTelefonica;
    private javax.swing.JLabel lblCodigoActualizarOperadoraTelefonica;
    private javax.swing.JLabel lblNombreActualizarOperadoraTelefonica;
    private javax.swing.JPanel panelActualizarOperadora;
    private javax.swing.JTextField txtCodigoActualizarOperadoraTelefonica;
    private javax.swing.JTextField txtNombreActualizarOperadoraTelefonica;
    // End of variables declaration//GEN-END:variables
}
