/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;


import ec.edu.ups.ejemplo.diez.controlador.PersonaControlador;
import ec.edu.ups.ejemplo.diez.modelo.Persona;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaBuscarPersona extends javax.swing.JInternalFrame {

    private PersonaControlador personaControlador;
    
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaBuscarPersona(PersonaControlador personaControlador) {
        initComponents();
        this.personaControlador = personaControlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPersona = new javax.swing.JPanel();
        lblCedulaBuscarPersona = new javax.swing.JLabel();
        lblFechaNacimientoBuscarPersona = new javax.swing.JLabel();
        lblNombreBuscarPersona = new javax.swing.JLabel();
        txtCedulaBuscarPersona = new javax.swing.JTextField();
        txtNombreBuscarPersona = new javax.swing.JTextField();
        txtFechaNacimientoCrearPersona = new javax.swing.JTextField();
        btnBuscarBuscarPersona = new javax.swing.JButton();
        btnCancelarBuscarPersona = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelPersona.setBackground(new java.awt.Color(204, 204, 204));
        panelPersona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        panelPersona.setToolTipText("Buscar Persona");

        lblCedulaBuscarPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblCedulaBuscarPersona.setText("Ingrese la Cedula:");

        lblFechaNacimientoBuscarPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblFechaNacimientoBuscarPersona.setText("La Fecha de Nacimiento es:");

        lblNombreBuscarPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblNombreBuscarPersona.setText("El Nombre es:");

        txtCedulaBuscarPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCedulaBuscarPersona.setToolTipText("Ingrese la cedula de la persona a buscar");
        txtCedulaBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaBuscarPersonaActionPerformed(evt);
            }
        });

        txtNombreBuscarPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreBuscarPersona.setToolTipText("");
        txtNombreBuscarPersona.setEnabled(false);
        txtNombreBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarPersonaActionPerformed(evt);
            }
        });

        txtFechaNacimientoCrearPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFechaNacimientoCrearPersona.setToolTipText("Ingrese la fecha de nacimiento de la nueva persona (01/01/2004)");
        txtFechaNacimientoCrearPersona.setEnabled(false);
        txtFechaNacimientoCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoCrearPersonaActionPerformed(evt);
            }
        });

        btnBuscarBuscarPersona.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarBuscarPersona.setText(" Buscar");
        btnBuscarBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBuscarPersonaActionPerformed(evt);
            }
        });

        btnCancelarBuscarPersona.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarBuscarPersona.setText("Cancelar");
        btnCancelarBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonaLayout = new javax.swing.GroupLayout(panelPersona);
        panelPersona.setLayout(panelPersonaLayout);
        panelPersonaLayout.setHorizontalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimientoBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedulaBuscarPersona))
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedulaBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscarBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPersonaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaNacimientoCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(btnCancelarBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        panelPersonaLayout.setVerticalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedulaBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimientoCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnCancelarBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBuscarPersonaActionPerformed
        
        
        String cedula = txtCedulaBuscarPersona.getText();
        Persona personita = personaControlador.buscar(cedula);
        if(personita != null){
            txtNombreBuscarPersona.setText(personita.getNombre());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaNacimiento = sdf.format(personita.getFechaNcaimiento().getTime());
            txtFechaNacimientoCrearPersona.setText(fechaNacimiento);
        }else{
             JOptionPane.showMessageDialog(this, "La persona con cedula" + cedula + "no existe");    
             }
        
    }//GEN-LAST:event_btnBuscarBuscarPersonaActionPerformed

    private void btnCancelarBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarPersonaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarBuscarPersonaActionPerformed

    private void txtCedulaBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscarPersonaActionPerformed

    private void txtFechaNacimientoCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoCrearPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoCrearPersonaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNombreBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarPersonaActionPerformed

    private void limpiarCampos(){
        this.txtCedulaBuscarPersona.setText("");
        this.txtNombreBuscarPersona.setText("");
        this.txtFechaNacimientoCrearPersona.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBuscarPersona;
    private javax.swing.JButton btnCancelarBuscarPersona;
    private javax.swing.JLabel lblCedulaBuscarPersona;
    private javax.swing.JLabel lblFechaNacimientoBuscarPersona;
    private javax.swing.JLabel lblNombreBuscarPersona;
    private javax.swing.JPanel panelPersona;
    private javax.swing.JTextField txtCedulaBuscarPersona;
    private javax.swing.JTextField txtFechaNacimientoCrearPersona;
    private javax.swing.JTextField txtNombreBuscarPersona;
    // End of variables declaration//GEN-END:variables
}
