/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;


import ec.edu.ups.ejemplo.diez.controlador.PersonaControlador;
import ec.edu.ups.ejemplo.diez.modelo.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaCrearPersona extends javax.swing.JInternalFrame {

    private PersonaControlador personaControlador;
    
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaCrearPersona(PersonaControlador personaControlador) {
        initComponents();
        this.personaControlador = personaControlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPersona = new javax.swing.JPanel();
        lblCedulaCrearPersona = new javax.swing.JLabel();
        lblFechaNacimientoCrearPersona = new javax.swing.JLabel();
        lblNombreCrearPersona = new javax.swing.JLabel();
        txtCedulaCrearPersona = new javax.swing.JTextField();
        txtNombreCrearPersona = new javax.swing.JTextField();
        txtFechaNacimientoCrearPersona = new javax.swing.JTextField();
        btnAceptarCrearPersona = new javax.swing.JButton();
        btnCancelarCrearPersona = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelPersona.setBackground(new java.awt.Color(204, 204, 204));
        panelPersona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Nueva Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        panelPersona.setToolTipText("Crear Nueva Persona");

        lblCedulaCrearPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblCedulaCrearPersona.setText("Cedula:");

        lblFechaNacimientoCrearPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona.setText("Fecha de Nacimiento:");

        lblNombreCrearPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblNombreCrearPersona.setText("Nombre:");

        txtCedulaCrearPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCedulaCrearPersona.setToolTipText("Ingrese la cedula de la nueva persona");
        txtCedulaCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCrearPersonaActionPerformed(evt);
            }
        });

        txtNombreCrearPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreCrearPersona.setToolTipText("Ingrese el nombre de la nueva persona");
        txtNombreCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCrearPersonaActionPerformed(evt);
            }
        });

        txtFechaNacimientoCrearPersona.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFechaNacimientoCrearPersona.setToolTipText("Ingrese la fecha de nacimiento de la nueva persona (01/01/2004)");
        txtFechaNacimientoCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoCrearPersonaActionPerformed(evt);
            }
        });

        btnAceptarCrearPersona.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptarCrearPersona.setText("Aceptar");
        btnAceptarCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearPersonaActionPerformed(evt);
            }
        });

        btnCancelarCrearPersona.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarCrearPersona.setText("Cancelar");
        btnCancelarCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonaLayout = new javax.swing.GroupLayout(panelPersona);
        panelPersona.setLayout(panelPersonaLayout);
        panelPersonaLayout.setHorizontalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaCrearPersona)
                            .addComponent(lblNombreCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimientoCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombreCrearPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFechaNacimientoCrearPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCedulaCrearPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelPersonaLayout.setVerticalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedulaCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimientoCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearPersonaActionPerformed
        
        
        String cedula = txtCedulaCrearPersona.getText();
        String nombre = txtNombreCrearPersona.getText();
        String fechaNacimiento = txtFechaNacimientoCrearPersona.getText();
        GregorianCalendar calendar = new GregorianCalendar();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date fecha = sdf.parse(fechaNacimiento);
            calendar.setTime(fecha);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Error al convertir la fecha");
        }
        Persona personita = new Persona();
        personita.setCedula(cedula);
        personita.setNombre(nombre);
        personita.setFechaNcaimiento(calendar);
        personaControlador.crear(personita);
        
        
        JOptionPane.showMessageDialog(this, "La persona ha sido creada exitosamente! :D ");
        this.limpiarCampos();
        
    }//GEN-LAST:event_btnAceptarCrearPersonaActionPerformed

    private void btnCancelarCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearPersonaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCrearPersonaActionPerformed

    private void txtCedulaCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCrearPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCrearPersonaActionPerformed

    private void txtNombreCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCrearPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCrearPersonaActionPerformed

    private void txtFechaNacimientoCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoCrearPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoCrearPersonaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void limpiarCampos(){
        this.txtCedulaCrearPersona.setText("");
        this.txtNombreCrearPersona.setText("");
        this.txtFechaNacimientoCrearPersona.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCrearPersona;
    private javax.swing.JButton btnCancelarCrearPersona;
    private javax.swing.JLabel lblCedulaCrearPersona;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona;
    private javax.swing.JLabel lblNombreCrearPersona;
    private javax.swing.JPanel panelPersona;
    private javax.swing.JTextField txtCedulaCrearPersona;
    private javax.swing.JTextField txtFechaNacimientoCrearPersona;
    private javax.swing.JTextField txtNombreCrearPersona;
    // End of variables declaration//GEN-END:variables
}
