/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;


import ec.edu.ups.ejemplo.diez.controlador.OperadoraTelefonicaControlador;
import ec.edu.ups.ejemplo.diez.controlador.PersonaControlador;
import ec.edu.ups.ejemplo.diez.modelo.OperadoraTelefonica;
import ec.edu.ups.ejemplo.diez.modelo.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaBuscarOperadoraTelefonica extends javax.swing.JInternalFrame {

    private OperadoraTelefonicaControlador operadoraTelefonicaControlador;
    
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaBuscarOperadoraTelefonica(OperadoraTelefonicaControlador operadoraTelefonicaControlador) {
        initComponents();
        this.operadoraTelefonicaControlador = operadoraTelefonicaControlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOperadoraTelefonica = new javax.swing.JPanel();
        lblCedulaBuscarOperadoraPersona = new javax.swing.JLabel();
        lblNombreBuscarOperadora = new javax.swing.JLabel();
        txtCodigoBuscarOperadoraTelefonica = new javax.swing.JTextField();
        txtNombreBuscarOperadoraTelefonica = new javax.swing.JTextField();
        btnBuscarBuscarOperadoraTelefonica = new javax.swing.JButton();
        btnCancelarBuscarOperadoraTelefonica = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelOperadoraTelefonica.setBackground(new java.awt.Color(204, 204, 204));
        panelOperadoraTelefonica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Operadora Telefonica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        panelOperadoraTelefonica.setToolTipText("Buscar Persona");

        lblCedulaBuscarOperadoraPersona.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblCedulaBuscarOperadoraPersona.setText("Ingrese el Codigo:");

        lblNombreBuscarOperadora.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblNombreBuscarOperadora.setText("El Nombre es:");

        txtCodigoBuscarOperadoraTelefonica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoBuscarOperadoraTelefonica.setToolTipText("Ingrese la cedula de la persona a buscar");
        txtCodigoBuscarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBuscarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        txtNombreBuscarOperadoraTelefonica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreBuscarOperadoraTelefonica.setToolTipText("");
        txtNombreBuscarOperadoraTelefonica.setEnabled(false);
        txtNombreBuscarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        btnBuscarBuscarOperadoraTelefonica.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarBuscarOperadoraTelefonica.setText(" Buscar");
        btnBuscarBuscarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBuscarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        btnCancelarBuscarOperadoraTelefonica.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarBuscarOperadoraTelefonica.setText("Cancelar");
        btnCancelarBuscarOperadoraTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBuscarOperadoraTelefonicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperadoraTelefonicaLayout = new javax.swing.GroupLayout(panelOperadoraTelefonica);
        panelOperadoraTelefonica.setLayout(panelOperadoraTelefonicaLayout);
        panelOperadoraTelefonicaLayout.setHorizontalGroup(
            panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperadoraTelefonicaLayout.createSequentialGroup()
                .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperadoraTelefonicaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreBuscarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedulaBuscarOperadoraPersona))
                        .addGap(132, 132, 132)
                        .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnBuscarBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOperadoraTelefonicaLayout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(btnCancelarBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        panelOperadoraTelefonicaLayout.setVerticalGroup(
            panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperadoraTelefonicaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedulaBuscarOperadoraPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(panelOperadoraTelefonicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBuscarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(btnCancelarBuscarOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperadoraTelefonica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarBuscarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBuscarOperadoraTelefonicaActionPerformed
        
        
        String codigo = txtCodigoBuscarOperadoraTelefonica.getText();
        OperadoraTelefonica operadoraTelefonica = operadoraTelefonicaControlador.buscar(Integer.parseInt(codigo));
        if(operadoraTelefonica != null){
            txtNombreBuscarOperadoraTelefonica.setText(operadoraTelefonica.getNombre());
        }else{
             JOptionPane.showMessageDialog(this, "La operadora con codigo" + codigo + "no existe");    
             }
        
    }//GEN-LAST:event_btnBuscarBuscarOperadoraTelefonicaActionPerformed

    private void btnCancelarBuscarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarOperadoraTelefonicaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarBuscarOperadoraTelefonicaActionPerformed

    private void txtCodigoBuscarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBuscarOperadoraTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBuscarOperadoraTelefonicaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNombreBuscarOperadoraTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarOperadoraTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarOperadoraTelefonicaActionPerformed

    private void limpiarCampos(){
        this.txtCodigoBuscarOperadoraTelefonica.setText("");
        this.txtNombreBuscarOperadoraTelefonica.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBuscarOperadoraTelefonica;
    private javax.swing.JButton btnCancelarBuscarOperadoraTelefonica;
    private javax.swing.JLabel lblCedulaBuscarOperadoraPersona;
    private javax.swing.JLabel lblNombreBuscarOperadora;
    private javax.swing.JPanel panelOperadoraTelefonica;
    private javax.swing.JTextField txtCodigoBuscarOperadoraTelefonica;
    private javax.swing.JTextField txtNombreBuscarOperadoraTelefonica;
    // End of variables declaration//GEN-END:variables
}
