/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;

import ec.edu.ups.ejemplo.diez.controlador.PersonaControlador;
import ec.edu.ups.ejemplo.diez.modelo.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaActualizarPersona extends javax.swing.JInternalFrame {

    private PersonaControlador personaControlador;

    /**
     * Creates new form VentanaActualizarPersona
     */
    public VentanaActualizarPersona(PersonaControlador personaControlador) {
        initComponents();
        this.personaControlador = personaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCedulaActualizarPersona = new javax.swing.JLabel();
        lblNombreActualizarPersona = new javax.swing.JLabel();
        lblFechaNacimientoActualizarPersona = new javax.swing.JLabel();
        txtCedulaActualizarPersona = new javax.swing.JTextField();
        txtNombreActualizarPersona = new javax.swing.JTextField();
        txtFechaNacimientoActualizarPersona = new javax.swing.JTextField();
        btnActualizarActualizarPersona = new javax.swing.JButton();
        btnCancelarActualizarPersona = new javax.swing.JButton();
        btnBuscarActualizarPersona = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        lblCedulaActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCedulaActualizarPersona.setText("Cedula:");

        lblNombreActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombreActualizarPersona.setText("Nombre:");

        lblFechaNacimientoActualizarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFechaNacimientoActualizarPersona.setText("Fecha de Nacimiento:");

        txtCedulaActualizarPersona.setToolTipText("Ingrese la nueva cedula de la persona");
        txtCedulaActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActualizarPersonaActionPerformed(evt);
            }
        });

        txtNombreActualizarPersona.setToolTipText("Ingrese el nuevo nombre de de la persona");
        txtNombreActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarPersonaActionPerformed(evt);
            }
        });

        txtFechaNacimientoActualizarPersona.setToolTipText("Ingrese la nueva fecha de nacimineto de la persona");

        btnActualizarActualizarPersona.setText("Actualizar");
        btnActualizarActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActualizarPersonaActionPerformed(evt);
            }
        });

        btnCancelarActualizarPersona.setText("Cancelar");
        btnCancelarActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarPersonaActionPerformed(evt);
            }
        });

        btnBuscarActualizarPersona.setText("Buscar");
        btnBuscarActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActualizarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedulaActualizarPersona)
                    .addComponent(lblNombreActualizarPersona)
                    .addComponent(lblFechaNacimientoActualizarPersona))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreActualizarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtFechaNacimientoActualizarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtCedulaActualizarPersona)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizarActualizarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarActualizarPersona)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarActualizarPersona)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedulaActualizarPersona)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarActualizarPersona)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizarPersona)
                    .addComponent(txtNombreActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoActualizarPersona)
                    .addComponent(txtFechaNacimientoActualizarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarActualizarPersona)
                    .addComponent(btnCancelarActualizarPersona))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizarPersonaActionPerformed

    private void txtCedulaActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActualizarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActualizarPersonaActionPerformed

    private void btnActualizarActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActualizarPersonaActionPerformed
        
        
        String cedula = txtCedulaActualizarPersona.getText();
        String nombre = txtNombreActualizarPersona.getText();
        String fechaNacimiento = txtFechaNacimientoActualizarPersona.getText();
        
        Date fechaUno;
        GregorianCalendar fechaFinal = new GregorianCalendar();
        
        try {
            fechaUno = new SimpleDateFormat("dd/MM/yyyy").parse(fechaNacimiento);            
            fechaFinal.setTime(fechaUno);
        } catch (ParseException ex) {
            System.out.println("Error: no se pudo convertir la fecha");
        }
                
        Persona personita = new Persona();
        personita.setCedula(cedula);
        personita.setNombre(nombre);
        personita.setFechaNcaimiento(fechaFinal);
        
        if(personaControlador.actualizar(personita)){
            JOptionPane.showMessageDialog(this, "La persona ha sido actualizada exitosamente! :)");
            this.limpiarCampos();   
            this.cambiarEstadoCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "La persona no ha sido actualizada! :(");
        }

    }//GEN-LAST:event_btnActualizarActualizarPersonaActionPerformed

    private void btnCancelarActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarPersonaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActualizarPersonaActionPerformed

    private void btnBuscarActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarPersonaActionPerformed
        String cedula = txtCedulaActualizarPersona.getText();
        Persona personita = personaControlador.buscar(cedula);
        if (personita != null) {
            txtNombreActualizarPersona.setText(personita.getNombre());
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String fechaNacimiento = format.format(personita.getFechaNcaimiento().getTime());
            txtFechaNacimientoActualizarPersona.setText(fechaNacimiento);
            this.cambiarEstadoCampos(true);
        } else {
            JOptionPane.showMessageDialog(this, "La persona con cedula " + cedula + " no ha sido encontrada!");
        }
    }//GEN-LAST:event_btnBuscarActualizarPersonaActionPerformed
    private void limpiarCampos() {
        this.txtCedulaActualizarPersona.setText("");
        this.txtNombreActualizarPersona.setText("");
        this.txtFechaNacimientoActualizarPersona.setText("");
    }

    private void cambiarEstadoCampos(boolean estado) {
        this.txtCedulaActualizarPersona.setEnabled(estado);
        this.txtNombreActualizarPersona.setEnabled(estado);
        this.txtFechaNacimientoActualizarPersona.setEnabled(estado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActualizarPersona;
    private javax.swing.JButton btnBuscarActualizarPersona;
    private javax.swing.JButton btnCancelarActualizarPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedulaActualizarPersona;
    private javax.swing.JLabel lblFechaNacimientoActualizarPersona;
    private javax.swing.JLabel lblNombreActualizarPersona;
    private javax.swing.JTextField txtCedulaActualizarPersona;
    private javax.swing.JTextField txtFechaNacimientoActualizarPersona;
    private javax.swing.JTextField txtNombreActualizarPersona;
    // End of variables declaration//GEN-END:variables
}
