/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista;

import ec.edu.ups.ejemplo.diez.controlador.OperadoraTelefonicaControlador;
import ec.edu.ups.ejemplo.diez.modelo.OperadoraTelefonica;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaEliminarOperadoraTelefonica extends javax.swing.JInternalFrame {

    private OperadoraTelefonicaControlador operadoraTelefonicaControlador;

    /**
     * Creates new form VentanaActualizarPersona
     */
    public VentanaEliminarOperadoraTelefonica(OperadoraTelefonicaControlador operadoraTelefonicaControlador) {
        initComponents();
        this.operadoraTelefonicaControlador = operadoraTelefonicaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigoEliminarOperadora = new javax.swing.JLabel();
        lblNombreEliminarPersona = new javax.swing.JLabel();
        txtCodigoEliminarOperadora = new javax.swing.JTextField();
        txtNombreEliminarOperadora = new javax.swing.JTextField();
        btnAceptarEliminarPersona = new javax.swing.JButton();
        btnCancelarEliminarPersona = new javax.swing.JButton();
        btnBuscarEliminarPersona = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Operadora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        lblCodigoEliminarOperadora.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCodigoEliminarOperadora.setText("Codigo de la operadora:");

        lblNombreEliminarPersona.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombreEliminarPersona.setText("Nombre:");

        txtCodigoEliminarOperadora.setToolTipText("Ingrese la nueva cedula de la persona");
        txtCodigoEliminarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEliminarOperadoraActionPerformed(evt);
            }
        });

        txtNombreEliminarOperadora.setToolTipText("Ingrese el nuevo nombre de de la persona");
        txtNombreEliminarOperadora.setEnabled(false);
        txtNombreEliminarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEliminarOperadoraActionPerformed(evt);
            }
        });

        btnAceptarEliminarPersona.setText("Eliminar");
        btnAceptarEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEliminarPersonaActionPerformed(evt);
            }
        });

        btnCancelarEliminarPersona.setText("Cancelar");
        btnCancelarEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEliminarPersonaActionPerformed(evt);
            }
        });

        btnBuscarEliminarPersona.setText("Buscar");
        btnBuscarEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoEliminarOperadora)
                    .addComponent(lblNombreEliminarPersona))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptarEliminarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEliminarPersona))
                    .addComponent(txtNombreEliminarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEliminarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarEliminarPersona)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEliminarOperadora)
                    .addComponent(txtCodigoEliminarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminarPersona))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEliminarPersona)
                    .addComponent(txtNombreEliminarOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarEliminarPersona)
                    .addComponent(btnCancelarEliminarPersona))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEliminarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEliminarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEliminarOperadoraActionPerformed

    private void txtCodigoEliminarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEliminarOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEliminarOperadoraActionPerformed

    private void btnAceptarEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEliminarPersonaActionPerformed
        String codigo = txtCodigoEliminarOperadora.getText();
        int respuesta = JOptionPane.showConfirmDialog(this, "Estás seguro que deseas eliminar la operadora? ");
        if (respuesta == JOptionPane.YES_OPTION) {
            if (operadoraTelefonicaControlador.eliminar(codigo)) {
                JOptionPane.showMessageDialog(this, "La operadora ha sido eliminada exitosamente! :D ");
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "La operadora con codigo" + codigo + "no existe");
            }
        }
    }//GEN-LAST:event_btnAceptarEliminarPersonaActionPerformed

    private void btnCancelarEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEliminarPersonaActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarEliminarPersonaActionPerformed

    private void btnBuscarEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarPersonaActionPerformed
        int codigo = Integer.parseInt(txtCodigoEliminarOperadora.getText());
        OperadoraTelefonica operadoraTelefonica = operadoraTelefonicaControlador.buscar(codigo);
        
        if(operadoraTelefonica != null){
            txtNombreEliminarOperadora.setText(operadoraTelefonica.getNombre());
            JOptionPane.showMessageDialog(this, "La persona ha sido encontrada exitosamente! :D ");
            
        }else{
            JOptionPane.showMessageDialog(this, "La persona con cedula" + codigo + "no existe");
        }
    }//GEN-LAST:event_btnBuscarEliminarPersonaActionPerformed

    private void limpiarCampos() {
        this.txtCodigoEliminarOperadora.setText("");
        this.txtNombreEliminarOperadora.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEliminarPersona;
    private javax.swing.JButton btnBuscarEliminarPersona;
    private javax.swing.JButton btnCancelarEliminarPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoEliminarOperadora;
    private javax.swing.JLabel lblNombreEliminarPersona;
    private javax.swing.JTextField txtCodigoEliminarOperadora;
    private javax.swing.JTextField txtNombreEliminarOperadora;
    // End of variables declaration//GEN-END:variables
}
