/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.java.ejemplo.diez.vista.telefono;


import ec.edu.ups.ejemplo.diez.controlador.OperadoraTelefonicaControlador;
import ec.edu.ups.ejemplo.diez.controlador.PersonaControlador;
import ec.edu.ups.ejemplo.diez.controlador.TelefonoControlador;
import ec.edu.ups.ejemplo.diez.modelo.OperadoraTelefonica;
import ec.edu.ups.ejemplo.diez.modelo.Persona;
import ec.edu.ups.ejemplo.diez.modelo.Telefono;
import ec.edu.ups.ejemplo.diez.modelo.TipoTelefono;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaBuscarTelefono extends javax.swing.JInternalFrame {
    
    private TelefonoControlador telefonoControlador;
    private PersonaControlador personaControlador;
    private OperadoraTelefonicaControlador operadoraTelefonicaControlador;
    private OperadoraTelefonica operadoraTelefonicaSeleccionada;
    private Persona personaSeleccionada;
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaBuscarTelefono(TelefonoControlador telefonoControlador, PersonaControlador personaControlador, OperadoraTelefonicaControlador operadoraTelefonicaControlador) {
        initComponents();
        this.telefonoControlador = telefonoControlador;
        this.personaControlador = personaControlador;
        this.operadoraTelefonicaControlador = operadoraTelefonicaControlador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearTelefono1 = new javax.swing.JPanel();
        lblCedulaCrearPersona1 = new javax.swing.JLabel();
        lblFechaNacimientoCrearPersona1 = new javax.swing.JLabel();
        lblNombreCrearPersona1 = new javax.swing.JLabel();
        txtNumeroCrearTelefono1 = new javax.swing.JTextField();
        txtTipoCrearTelefono1 = new javax.swing.JTextField();
        txtFechaNacimientoCrearPersona1 = new javax.swing.JTextField();
        btnAceptarCrearTelefono1 = new javax.swing.JButton();
        btnCancelarCrearTelefono1 = new javax.swing.JButton();
        buttonGroupTelefono = new javax.swing.ButtonGroup();
        panelCrearTelefono2 = new javax.swing.JPanel();
        lblNumeroBuscarTelefono = new javax.swing.JLabel();
        lblOperadoraBuscarTelefono = new javax.swing.JLabel();
        lblTipoBuscarTelefono = new javax.swing.JLabel();
        txtNumeroBuscarTelefono = new javax.swing.JTextField();
        btnAceptarBuscarTelefono = new javax.swing.JButton();
        txtTipoBuscarTelefono = new javax.swing.JTextField();
        txtOperadoraBuscarTelefono = new javax.swing.JTextField();
        lblNombreBuscarPersona = new javax.swing.JLabel();
        txtNombreBuscarTelefono = new javax.swing.JTextField();
        btnCancelarBuscarTelefono = new javax.swing.JButton();

        panelCrearTelefono1.setBackground(new java.awt.Color(204, 204, 204));
        panelCrearTelefono1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Nueva Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        panelCrearTelefono1.setToolTipText("Crear Nueva Persona");

        lblCedulaCrearPersona1.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblCedulaCrearPersona1.setText("Numero:");

        lblFechaNacimientoCrearPersona1.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona1.setText("Fecha de Nacimiento:");

        lblNombreCrearPersona1.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblNombreCrearPersona1.setText("Tipo:");

        txtNumeroCrearTelefono1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeroCrearTelefono1.setToolTipText("Ingrese la cedula de la nueva persona");
        txtNumeroCrearTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCrearTelefono1ActionPerformed(evt);
            }
        });

        txtTipoCrearTelefono1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTipoCrearTelefono1.setToolTipText("Ingrese el nombre de la nueva persona");
        txtTipoCrearTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoCrearTelefono1ActionPerformed(evt);
            }
        });

        txtFechaNacimientoCrearPersona1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFechaNacimientoCrearPersona1.setToolTipText("Ingrese la fecha de nacimiento de la nueva persona (01/01/2004)");
        txtFechaNacimientoCrearPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoCrearPersona1ActionPerformed(evt);
            }
        });

        btnAceptarCrearTelefono1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptarCrearTelefono1.setText("Aceptar");
        btnAceptarCrearTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearTelefono1ActionPerformed(evt);
            }
        });

        btnCancelarCrearTelefono1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarCrearTelefono1.setText("Cancelar");
        btnCancelarCrearTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearTelefono1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearTelefono1Layout = new javax.swing.GroupLayout(panelCrearTelefono1);
        panelCrearTelefono1.setLayout(panelCrearTelefono1Layout);
        panelCrearTelefono1Layout.setHorizontalGroup(
            panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefono1Layout.createSequentialGroup()
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTelefono1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaCrearPersona1)
                            .addComponent(lblNombreCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimientoCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearTelefono1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTipoCrearTelefono1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFechaNacimientoCrearPersona1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroCrearTelefono1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelCrearTelefono1Layout.setVerticalGroup(
            panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefono1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedulaCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimientoCrearPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelCrearTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCrearTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Telefono");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCrearTelefono2.setBackground(new java.awt.Color(204, 204, 204));
        panelCrearTelefono2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        panelCrearTelefono2.setToolTipText("Buscar Telefono");

        lblNumeroBuscarTelefono.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblNumeroBuscarTelefono.setText("Numero:");

        lblOperadoraBuscarTelefono.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblOperadoraBuscarTelefono.setText("Operadora:");

        lblTipoBuscarTelefono.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblTipoBuscarTelefono.setText("Tipo:");

        txtNumeroBuscarTelefono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeroBuscarTelefono.setToolTipText("");
        txtNumeroBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroBuscarTelefonoActionPerformed(evt);
            }
        });

        btnAceptarBuscarTelefono.setText("Buscar");
        btnAceptarBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarBuscarTelefonoActionPerformed(evt);
            }
        });

        txtTipoBuscarTelefono.setEditable(false);
        txtTipoBuscarTelefono.setToolTipText("");
        txtTipoBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoBuscarTelefonoActionPerformed(evt);
            }
        });

        txtOperadoraBuscarTelefono.setEditable(false);

        lblNombreBuscarPersona.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreBuscarPersona.setText("Nombre:");

        txtNombreBuscarTelefono.setEditable(false);

        javax.swing.GroupLayout panelCrearTelefono2Layout = new javax.swing.GroupLayout(panelCrearTelefono2);
        panelCrearTelefono2.setLayout(panelCrearTelefono2Layout);
        panelCrearTelefono2Layout.setHorizontalGroup(
            panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefono2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroBuscarTelefono)
                    .addComponent(lblTipoBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOperadoraBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTelefono2Layout.createSequentialGroup()
                        .addComponent(txtNombreBuscarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addGap(264, 264, 264))
                    .addGroup(panelCrearTelefono2Layout.createSequentialGroup()
                        .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroBuscarTelefono)
                            .addComponent(txtTipoBuscarTelefono)
                            .addComponent(txtOperadoraBuscarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(btnAceptarBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCrearTelefono2Layout.setVerticalGroup(
            panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTelefono2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTelefono2Layout.createSequentialGroup()
                        .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptarBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearTelefono2Layout.createSequentialGroup()
                        .addComponent(txtNumeroBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperadoraBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperadoraBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearTelefono2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCancelarBuscarTelefono.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(btnCancelarBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCrearTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCrearTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnCancelarBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNumeroCrearTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCrearTelefono1ActionPerformed
        
    }//GEN-LAST:event_txtNumeroCrearTelefono1ActionPerformed

    private void txtTipoCrearTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoCrearTelefono1ActionPerformed
        
    }//GEN-LAST:event_txtTipoCrearTelefono1ActionPerformed

    private void txtFechaNacimientoCrearPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoCrearPersona1ActionPerformed
        
    }//GEN-LAST:event_txtFechaNacimientoCrearPersona1ActionPerformed

    private void btnAceptarCrearTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearTelefono1ActionPerformed
       
    }//GEN-LAST:event_btnAceptarCrearTelefono1ActionPerformed

    private void btnCancelarCrearTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCrearTelefono1ActionPerformed

    private void txtNumeroBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroBuscarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroBuscarTelefonoActionPerformed

    private void btnAceptarBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBuscarTelefonoActionPerformed
        String numero = txtNumeroBuscarTelefono.getText();
        if(numero.isEmpty()){
            JOptionPane.showMessageDialog(this,"Rellenar los campos es obligatorio. ");
        }else{
            Telefono telefono = telefonoControlador.buscar(numero);
            if(telefono != null){
                txtTipoBuscarTelefono.setText(telefono.getTipo().toString());
                txtNombreBuscarTelefono.setText(telefono.getUnaPersona().toString());
                txtOperadoraBuscarTelefono.setText(telefono.getUnaOperadoraTelefonica().toString());
            }
        }
    }//GEN-LAST:event_btnAceptarBuscarTelefonoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void txtTipoBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoBuscarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoBuscarTelefonoActionPerformed

    private void limpiarCampos(){
    }
    
    private void limpiarCamposTelefono(){
        this.txtNumeroBuscarTelefono.setText("");
        this.txtNombreBuscarTelefono.setText("");
        this.txtOperadoraBuscarTelefono.setText("");
        this.txtTipoBuscarTelefono.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarBuscarTelefono;
    private javax.swing.JButton btnAceptarCrearTelefono1;
    private javax.swing.JButton btnCancelarBuscarTelefono;
    private javax.swing.JButton btnCancelarCrearTelefono1;
    private javax.swing.ButtonGroup buttonGroupTelefono;
    private javax.swing.JLabel lblCedulaCrearPersona1;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona1;
    private javax.swing.JLabel lblNombreBuscarPersona;
    private javax.swing.JLabel lblNombreCrearPersona1;
    private javax.swing.JLabel lblNumeroBuscarTelefono;
    private javax.swing.JLabel lblOperadoraBuscarTelefono;
    private javax.swing.JLabel lblTipoBuscarTelefono;
    private javax.swing.JPanel panelCrearTelefono1;
    private javax.swing.JPanel panelCrearTelefono2;
    private javax.swing.JTextField txtFechaNacimientoCrearPersona1;
    private javax.swing.JTextField txtNombreBuscarTelefono;
    private javax.swing.JTextField txtNumeroBuscarTelefono;
    private javax.swing.JTextField txtNumeroCrearTelefono1;
    private javax.swing.JTextField txtOperadoraBuscarTelefono;
    private javax.swing.JTextField txtTipoBuscarTelefono;
    private javax.swing.JTextField txtTipoCrearTelefono1;
    // End of variables declaration//GEN-END:variables
}
